ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'IN_PROGRESS',
ADD COLUMN IF NOT EXISTS priority VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
ADD COLUMN IF NOT EXISTS due_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS position BIGINT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS category VARCHAR(80),
ADD COLUMN IF NOT EXISTS assignee_email VARCHAR(255);

UPDATE tasks
SET status = CASE WHEN completed THEN 'DONE' ELSE 'IN_PROGRESS' END
WHERE status IS NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_position ON tasks(position);
