ALTER TABLE tasks
ADD COLUMN IF NOT EXISTS status VARCHAR(20),
ADD COLUMN IF NOT EXISTS priority VARCHAR(20),
ADD COLUMN IF NOT EXISTS due_date TIMESTAMP,
ADD COLUMN IF NOT EXISTS position BIGINT,
ADD COLUMN IF NOT EXISTS category VARCHAR(80),
ADD COLUMN IF NOT EXISTS assignee_email VARCHAR(255);

UPDATE tasks
SET status = CASE WHEN completed THEN 'DONE' ELSE 'IN_PROGRESS' END
WHERE status IS NULL;

UPDATE tasks
SET priority = 'MEDIUM'
WHERE priority IS NULL;

UPDATE tasks
SET position = id
WHERE position IS NULL;

ALTER TABLE tasks
ALTER COLUMN status SET DEFAULT 'IN_PROGRESS',
ALTER COLUMN status SET NOT NULL,
ALTER COLUMN priority SET DEFAULT 'MEDIUM',
ALTER COLUMN priority SET NOT NULL,
ALTER COLUMN position SET DEFAULT 0,
ALTER COLUMN position SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_tasks_due_date ON tasks(due_date);
CREATE INDEX IF NOT EXISTS idx_tasks_position ON tasks(position);
